Feat: Send A Package entity and auth guard fix
novareach-solutions/movemate pull request #80
Opened 2024-12-23 14:32 UTC by abdul-ahad12

## Description

SendPackageOrder Entity which aligns with the business needs

2024-12-24 20:56 UTC, shettydev requested changes

2024-12-24 20:56 UTC, shettydev commented on apps/backend/backend-main/src/app.module.ts
> +    // StripeModule,
Why was this removed?

2024-12-24 20:56 UTC, shettydev commented on apps/backend/backend-main/src/entity/Agent.ts
If an `Agent` is a type of `User` then shouldn't the user be deleted along with the `Agent`?

2024-12-24 20:56 UTC, shettydev commented on apps/backend/backend-main/src/entity/AgentDocument.ts
Similarly, the Documents related to the Agent should be deleted with `cascade` if the Agent no longer exists

2024-12-24 20:56 UTC, shettydev commented on apps/backend/backend-main/src/entity/AgentReview.ts
Same I think the review of the Agent should be deleted, else there will no reference to which user the review belongs to

2024-12-26 08:44 UTC, novareachsolutions commented on apps/backend/backend-main/src/entity/AgentDocument.ts
Hey yes, onDelete: "CASCADE", does that only

2024-12-26 08:45 UTC, novareachsolutions commented on apps/backend/backend-main/src/entity/AgentReview.ts
Hey yes, onDelete: "CASCADE", does that only

2024-12-30 15:43 UTC, amitravikumar approved these changes

2024-12-31 15:33 UTC, shettydev approved these changes

2024-12-31 17:12 UTC, merged